sudo: false
language: node_js
node_js:
- node
os:
- osx
- linux
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
- npm install -g vsce
script:
- npm run tslint
- node scripts/genAiKey.js
- echo "y" | vsce package
- npm test --silent
deploy:
- provider: releases
  skip_cleanup: true
  api_key: "$GIT_TOKEN"
  file_glob: true
  file: "*.vsix"
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux"
- provider: script
  skip_cleanup: true
  script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux && $TRAVIS_TAG =~ $ISPRODTAG"
env:
  global:
  - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$
  - secure: QIU9zRXZ3ncIjbUuUMqY+AAtf17m7utHgIh8dG8nbK2u6XY0V30f8PDsgwJraSIF6k7HLnaC50eDMmMR2cPbgb4COTa9xmVqf1CHKkbVpgsJIP+PmV5TUQ+tczu1B65NrRfL/8Wki1vLgTLqSGjN54dk1npnTwLP46vryCJ2jYGsjcVDNKtaM7y5PNTiMSOPOSKYRNw36RX52O3+toxweyM5a4/p4dYU44QYY76YmMrgV1g7TcThzHbFe5q6eWjmkKlKm1Ckqru0vpPOPgd99BtR6ORMarW5/1wVZsDgDpgi6KyvbTrcnRadjioqYkoRTiPjCgHoJPxLgAv1rY2a84H9IKhhpc5PUe6HK+mMAnZGHieodCSqHFWtS3cPPpeiqW0nJCUPX9GqikA/uo+NIBN8WBaqfDO7JPUzWDJFxXmC1A3mMPahc1dvzu8OtwbJjC///R5k9wbKld8WTbe4OovVkPgR3kyY9Bw3ERYGFy4+voXiZI2b6rwNPKWVMNs+ugkBHM57lBTI7sWa8k1T8gu60A3144iRGJtIlkBt6Ghs70hN+E41f8tcDxluXU+LTy1Nh8IVnRpsIo3N+u+kKq0QB7yASAHiRuy/6bNI7LPO1PV0KdCNolAbIFTeqO9WGskdlBMaybDidEyytLdQakj57XnIwO1mQqB4UUyogOI=
  - secure: FYAr4QWnc09SrZZ1M5u7i+t9MUuYfIqhw6tpeMwLXzxLkgCDfZKmkNS9rG+1eUb2IjThJvnMcy2s/AinpGAZ4Po3iSn+KT6CYrGY8ncUj3unXWY6TGua8mNu7PEvzObi8Q2s8gyAYEV+1cXU54woHzKnlPlnz3pc++Y+8CHsAaNU0f9dKWuBqsRjn9FTQtAk7hEWkbi0vR39J9o/QV5XXr8Mk+RoYo4YKIcRwjXLkO8RfUCHtE6c+UU+YVKHmFzFkzHVki2+awjtaswo13iu8x2hAnPLQmwd5XkSt8ygtxM+uNmvmsf/skekpuRwytmCYGkWIOIHgL4ngZXuVIfqasdzi5QgTOe6Wx/65ElebNLF/epB9UVbKSspqeMSOkShrgeD/p6I+Q0ccf3IcbopVUxeu6c6GIbd7jgIfllnNqdWNJUYgQEcQw5Hp3lETKbhXu786NL2s8GKKst1KY2g8c4R+mlWQFVPTAML7g3tprNE6jTIJtcHh7iY0nNkyB0P8AmrQd4xwmGuIptTP0qK97vL/ljzV1kgKbirlCUkteQrqEth2sqxp7CtADJ32EKn27o9Rbydlc/koU6PBtG+OwHxZy2X2+tAZdXjdf1TQUY1O0mA2XeaxZUsTsK9Kms5TNuT/78Nfg2WIG9RBTFvB9MvHabjajp5h4g0eUMxqYU=
