sudo: false
language: node_js
node_js:
  - "node"
os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  # To make CI pass: ms-rest-azure and ms-rest are not directly used in extension but in azure-account.api.d.ts
  - npm install ms-rest-azure
  - npm install ms-rest
  - npm run version
  - npm run vscode:prepublish

script:
  - npm run tslint
  # - npm test --silent