sudo: false
language: node_js
node_js:
- lts/*
services:
- docker
os:
- osx
- linux
before_install:
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    sudo apt-get install libsecret-1-dev
  fi
install:
- npm install
- npm install -g vsce
script:
- npm run tslint
- npm run compile
- node scripts/genAiKey.js
- echo "y" | vsce package
- npm test --silent
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    docker run -ti --rm -v $PWD:/mnt:ro dkhamsing/awesome_bot --allow-dupe --allow-redirect --skip-save-results `ls *.md` --white-list gitter.im
  fi
deploy:
- provider: releases
  skip_cleanup: true
  api_key: "$GIT_TOKEN"
  file_glob: true
  file: "*.vsix"
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux"
- provider: script
  skip_cleanup: true
  script: vsce publish -p $VSCE_TOKEN --packagePath *.vsix
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME == linux && $TRAVIS_TAG =~ $ISPRODTAG"
env:
  global:
  - ISPRODTAG=^v?[0-9]+\.[0-9]+\.[0-9]+$
  - secure: QIU9zRXZ3ncIjbUuUMqY+AAtf17m7utHgIh8dG8nbK2u6XY0V30f8PDsgwJraSIF6k7HLnaC50eDMmMR2cPbgb4COTa9xmVqf1CHKkbVpgsJIP+PmV5TUQ+tczu1B65NrRfL/8Wki1vLgTLqSGjN54dk1npnTwLP46vryCJ2jYGsjcVDNKtaM7y5PNTiMSOPOSKYRNw36RX52O3+toxweyM5a4/p4dYU44QYY76YmMrgV1g7TcThzHbFe5q6eWjmkKlKm1Ckqru0vpPOPgd99BtR6ORMarW5/1wVZsDgDpgi6KyvbTrcnRadjioqYkoRTiPjCgHoJPxLgAv1rY2a84H9IKhhpc5PUe6HK+mMAnZGHieodCSqHFWtS3cPPpeiqW0nJCUPX9GqikA/uo+NIBN8WBaqfDO7JPUzWDJFxXmC1A3mMPahc1dvzu8OtwbJjC///R5k9wbKld8WTbe4OovVkPgR3kyY9Bw3ERYGFy4+voXiZI2b6rwNPKWVMNs+ugkBHM57lBTI7sWa8k1T8gu60A3144iRGJtIlkBt6Ghs70hN+E41f8tcDxluXU+LTy1Nh8IVnRpsIo3N+u+kKq0QB7yASAHiRuy/6bNI7LPO1PV0KdCNolAbIFTeqO9WGskdlBMaybDidEyytLdQakj57XnIwO1mQqB4UUyogOI=
